<?php

namespace li3_location\core;


use lithium\util\Set;
use lithium\net\http\Service;

/**
 * A list of Countries and their iso-codes
 *
 */
class Countries extends \lithium\core\StaticObject {

	/**
	 * An array of countries, keyed of by their 2-letter isocode
	 *
	 * @var array
	 */
	protected static $_countries = array(
		"USA" =>  "US (United States)",
		"CA" =>  "Canada",
		"DE" =>  "Germany",
		"AF" =>  "Afghanistan",
		"AX" =>  "Aland",
		"AL" =>  "Albania",
		"DZ" =>  "Algeria",
		"AS" =>  "American Samoa",
		"AD" =>  "Andorra",
		"AO" =>  "Angola",
		"AI" =>  "Anguilla",
		"AG" =>  "Antigua and Barbuda",
		"AR" =>  "Argentina",
		"AM" =>  "Armenia",
		"AW" =>  "Aruba",
		"AC" =>  "Ascension",
		"AA" =>  "Australia",
		"AT" =>  "Austria",
		"BH" =>  "Bahrain",
		"BD" =>  "Bangladesh",
		"BB" =>  "Barbados",
		"BY" =>  "Belarus",
		"BE" =>  "Belgium",
		"BZ" =>  "Belize",
		"BJ" =>  "Benin",
		"BM" =>  "Bermuda",
		"BT" =>  "Bhutan",
		"BO" =>  "Bolivia",
		"BA" =>  "Bosnia and Herzegovina",
		"BW" =>  "Botswana",
		"BV" =>  "Bouvet Island",
		"BR" =>  "Brazil",
		"AQ" =>  "British Antarctic Territory",
		"IO" =>  "British Indian Ocean Territory",
		"VG" =>  "British Virgin Islands",
		"BN" =>  "Brunei",
		"BG" =>  "Bulgaria",
		"BF" =>  "Burkina Faso",
		"BI" =>  "Burundi",
		"KH" =>  "Cambodia",
		"CM" =>  "Cameroon",
		"CV" =>  "Cape Verde",
		"KY" =>  "Cayman Islands",
		"CF" =>  "Central African Republic",
		"TD" =>  "Chad",
		"CL" =>  "Chile",
		"CN" =>  "China",
		"CX" =>  "Christmas Island",
		"PF" =>  "Clipperton Island",
		"CC" =>  "Cocos (Keeling) Islands",
		"CO" =>  "Colombia",
		"KM" =>  "Comoros",
		"CK" =>  "Cook Islands",
		"AU" =>  "Coral Sea Islands",
		"CR" =>  "Costa Rica",
		"CI" =>  "Cote d'Ivoire (Ivory Coast)",
		"HR" =>  "Croatia",
		"CU" =>  "Cuba",
		"CZ" =>  "Czech Republic",
		"DK" =>  "Denmark",
		"DJ" =>  "Djibouti",
		"DM" =>  "Dominica",
		"DO" =>  "Dominican Republic",
		"EC" =>  "Ecuador",
		"EG" =>  "Egypt",
		"SV" =>  "El Salvador",
		"GQ" =>  "Equatorial Guinea",
		"ER" =>  "Eritrea",
		"EE" =>  "Estonia",
		"ET" =>  "Ethiopia",
		"FK" =>  "Falkland Islands (Islas Malvinas)",
		"FO" =>  "Faroe Islands",
		"FJ" =>  "Fiji",
		"FI" =>  "Finland",
		"FR" =>  "France",
		"GF" =>  "French Guiana",
		"TF" =>  "French Southern and Antarctic Lands",
		"GH" =>  "Ghana",
		"GI" =>  "Gibraltar",
		"GR" =>  "Greece",
		"GL" =>  "Greenland",
		"GD" =>  "Grenada",
		"GP" =>  "Guadeloupe",
		"GU" =>  "Guam",
		"GT" =>  "Guatemala",
		"GG" =>  "Guernsey",
		"GN" =>  "Guinea",
		"GW" =>  "Guinea-Bissau",
		"GY" =>  "Guyana",
		"HT" =>  "Haiti",
		"HM" =>  "Heard Island and McDonald Islands",
		"HN" =>  "Honduras",
		"HK" =>  "Hong Kong",
		"HU" =>  "Hungary",
		"IS" =>  "Iceland",
		"IN" =>  "India",
		"ID" =>  "Indonesia",
		"IR" =>  "Iran",
		"IQ" =>  "Iraq",
		"IE" =>  "Ireland",
		"IM" =>  "Isle of Man",
		"IL" =>  "Israel",
		"IT" =>  "Italy",
		"JM" =>  "Jamaica",
		"JP" =>  "Japan",
		"JE" =>  "Jersey",
		"JO" =>  "Jordan",
		"KZ" =>  "Kazakhstan",
		"KE" =>  "Kenya",
		"KI" =>  "Kiribati",
		"KO" =>  "Korea",
		"CS" =>  "Kosovo",
		"KW" =>  "Kuwait",
		"KG" =>  "Kyrgyzstan",
		"LA" =>  "Laos",
		"LV" =>  "Latvia",
		"LB" =>  "Lebanon",
		"LS" =>  "Lesotho",
		"LR" =>  "Liberia",
		"LY" =>  "Libya",
		"LI" =>  "Liechtenstein",
		"LT" =>  "Lithuania",
		"LU" =>  "Luxembourg",
		"MO" =>  "Macau",
		"MK" =>  "Macedonia",
		"MG" =>  "Madagascar",
		"MW" =>  "Malawi",
		"MY" =>  "Malaysia",
		"MV" =>  "Maldives",
		"ML" =>  "Mali",
		"MT" =>  "Malta",
		"MH" =>  "Marshall Islands",
		"MQ" =>  "Martinique",
		"MR" =>  "Mauritania",
		"MU" =>  "Mauritius",
		"YT" =>  "Mayotte",
		"MX" =>  "Mexico",
		"FM" =>  "Micronesia",
		"MC" =>  "Monaco",
		"MN" =>  "Mongolia",
		"ME" =>  "Montenegro",
		"MS" =>  "Montserrat",
		"MA" =>  "Morocco",
		"MZ" =>  "Mozambique",
		"MM" =>  "Myanmar (Burma)",
		"AZ" =>  "Nagorno-Karabakh",
		"NA" =>  "Namibia",
		"NR" =>  "Nauru",
		"NP" =>  "Nepal",
		"NL" =>  "Netherlands",
		"AN" =>  "Netherlands Antilles",
		"NC" =>  "New Caledonia",
		"NZ" =>  "New Zealand",
		"NI" =>  "Nicaragua",
		"NE" =>  "Niger",
		"NG" =>  "Nigeria",
		"NU" =>  "Niue",
		"NF" =>  "Norfolk Island",
		"CY" =>  "Northern Cyprus",
		"MP" =>  "Northern Mariana Islands",
		"NO" =>  "Norway",
		"OM" =>  "Oman",
		"PK" =>  "Pakistan",
		"PW" =>  "Palau",
		"PS" =>  "Palestinian Territories (Gaza Strip and West Bank)",
		"PA" =>  "Panama",
		"PG" =>  "Papua New Guinea",
		"PY" =>  "Paraguay",
		"PE" =>  "Peru",
		"PH" =>  "Philippines",
		"PN" =>  "Pitcairn Islands",
		"PL" =>  "Poland",
		"PT" =>  "Portugal",
		"MD" =>  "Pridnestrovie (Transnistria)",
		"PR" =>  "Puerto Rico",
		"QA" =>  "Qatar",
		"RE" =>  "Reunion",
		"RO" =>  "Romania",
		"RU" =>  "Russia",
		"RW" =>  "Rwanda",
		"SH" =>  "Saint Helena",
		"KN" =>  "Saint Kitts and Nevis",
		"LC" =>  "Saint Lucia",
		"PM" =>  "Saint Pierre and Miquelon",
		"VC" =>  "Saint Vincent and the Grenadines",
		"WS" =>  "Samoa",
		"SM" =>  "San Marino",
		"ST" =>  "Sao Tome and Principe",
		"SA" =>  "Saudi Arabia",
		"SN" =>  "Senegal",
		"RS" =>  "Serbia",
		"SC" =>  "Seychelles",
		"SL" =>  "Sierra Leone",
		"SG" =>  "Singapore",
		"SK" =>  "Slovakia",
		"SI" =>  "Slovenia",
		"SB" =>  "Solomon Islands",
		"SO" =>  "Somaliland",
		"ZA" =>  "South Africa",
		"GS" =>  "South Georgia and the South Sandwich Islands",
		"GE" =>  "South Ossetia",
		"ES" =>  "Spain",
		"LK" =>  "Sri Lanka",
		"SD" =>  "Sudan",
		"SR" =>  "Suriname",
		"SJ" =>  "Svalbard",
		"SZ" =>  "Swaziland",
		"SE" =>  "Sweden",
		"CH" =>  "Switzerland",
		"SY" =>  "Syria",
		"TW" =>  "Taiwan",
		"TJ" =>  "Tajikistan",
		"TZ" =>  "Tanzania",
		"TH" =>  "Thailand",
		"TL" =>  "Timor-Leste (East Timor)",
		"TG" =>  "Togo",
		"TK" =>  "Tokelau",
		"TO" =>  "Tonga",
		"TT" =>  "Trinidad and Tobago",
		"TA" =>  "Tristan da Cunha",
		"TN" =>  "Tunisia",
		"TR" =>  "Turkey",
		"TM" =>  "Turkmenistan",
		"TC" =>  "Turks and Caicos Islands",
		"TV" =>  "Tuvalu",
		"VI" =>  "U.S. Virgin Islands",
		"UG" =>  "Uganda",
		"UA" =>  "Ukraine",
		"AE" =>  "United Arab Emirates",
		"UK" =>  "UK (United Kingdom)",
		"UY" =>  "Uruguay",
		"UZ" =>  "Uzbekistan",
		"VU" =>  "Vanuatu",
		"VA" =>  "Vatican City",
		"VE" =>  "Venezuela",
		"VN" =>  "Viet Nam",
		"UM" =>  "Wake Island",
		"WF" =>  "Wallis and Futuna",
		"EH" =>  "Western Sahara",
		"YE" =>  "Yemen",
		"ZM" =>  "Zambia",
		"ZW" =>  "Zimbabwe",
	);

	/**
	 * Returns name of Country in english language for a given 2-letter isocode
	 *
	 * @param string $isocode 2-letter iso-code
	 * @param string $default what to return, if no country is found, defaults to false
	 * @return mixed name of country, false if not found
	 */
	public static function name($isocode, $default = false) {
		$isocode = strtoupper($isocode);
		if (!array_key_exists($isocode, self::$_countries)) {
			return $default;
		}
		return self::$_countries[$isocode];
	}

}
